spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: ITEMS-SERVICE
        uri: lb://ITEMS-SERVICE
        predicates:
        - Path=/item/**
    
server:
  port: 9191
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost